### PR TITLE
Sharing responsibility?

### PR DESCRIPTION
**Pull request by erictleung**
Hi @sourabh-joshi,

Thanks for maintaining this repository for all these years! I made the initial PR to auto-create the JSON object containing all email content https://github.com/sourabh-joshi/awesome-quincy-larson-emails/pull/1 and I'm also a moderator for freeCodeCamp (https://github.com/orgs/freeCodeCamp/people?query=erictleung)

I'm writing this "dummy PR" to open a discussion about the future of this repository. I couldn't help notice that it took over a month after the February 5th, 2024 commit (https://github.com/sourabh-joshi/awesome-quincy-larson-emails/commit/6848e00f51cae5ac91b260b2d05af68eaf6ae159) to make an update on the repo. As a repo maintainer myself, I know how much continued effort it takes to maintain a repo.

So I'm curious to learn how you're feeling about maintaining this repo, and if you would like any assistance in maintaining it. If you're okay continuing to maintain the repo, great. If you are open to some help, I'm happy to share some of that responsibility if you give me merge access to this repo. I have also talked with some freeCodeCamp Moderators and another option is for this repo to be maintained under the freeCodeCamp organization while also giving you full credit for starting and maintaining this repo for the past few years.

And once again, thanks for reading Quincy's emails and maintaining this repo for all these years.

Thanks,
Eric

### CODE REVIEW

**Comment by sourabh-joshi** [comment]
@erictleung Maintaining this repo under freeCodeCamp organization would be ideal. Let's get that done.

**Comment by raisedadead** [comment]
Hey @sourabh-joshi 

Thanks for the work you have been doing for the community and maintaining this helpful resource.

I am one of the staff members from freeCodeCamp and I can help with the process, can you transfer the repository to me `raisedadead` and I will have it moved into the freeCodeCamp GitHub org. 

You are able to verify my credentials here: https://github.com/orgs/freeCodeCamp/people?query=mrugesh


I will also send you an invite to the organization, please check your inbox.

Cheers!

**Comment by sourabh-joshi** [comment]
@raisedadead Have initiated the transfer. Please check on your end.

**Comment by raisedadead** [comment]
Hi @sourabh-joshi thanks for transferring this repo over to freeCodeCamp. 

We appreciate all of your hard work with this repository. And we are excited to see the community help maintain this awesome resource.

I have sent you an invite to the GitHub Org which you can accept by visiting your inbox or this page: https://github.com/freeCodeCamp

Cheers!

**Pull request closed without merging**
